from file_operations.file_operations import FileOperations
from data_operations.data_analysis import DataAnalyser
from shift_allocator.shift_allocator import ShiftAllocator
from prepare_output.prepare_shifts import PrepareShifts

if __name__ == "__main__":
    print("////////////////////////////////////////////////////////////////////////////////////////////////////////")
    print("Commencing Shift Allocation for the provided demand data ...........")
    print("////////////////////////////////////////////////////////////////////////////////////////////////////////")
    print("1. Reading the contents of the file..")
    file_operations = FileOperations()
    data = file_operations.read_csv_file()
    print("File Checks and Reading of Data Completed...")
    print("////////////////////////////////////////////////////////////////////////////////////////////////////////")
    print("2. Performing Data Cleaning, Checks and some basic preliminary Data Analysis...")
    data_analyser = DataAnalyser(data=data)
    data_analyser.perform_basic_data_analysis()
    print("Data Cleaning, checks and preliminary Data Analysis Complete..")
    print("////////////////////////////////////////////////////////////////////////////////////////////////////////")
    print("3 . Commencing allocation of shifts...")
    shift_allocator = ShiftAllocator(data=data)
    shift_allocator.check_allocation()
    allocated_shifts = shift_allocator.get_allocated_shifts()
    print("Shift combination identification complete..")
    print("////////////////////////////////////////////////////////////////////////////////////////////////////////")
    print("4. Preparing shifts compliant to expected output commencing...")
    shifts_preparer = PrepareShifts(allocated_shifts=allocated_shifts, demand_data=data)
    shifts_preparer.prepare_shifts()
    final_shift_information = shifts_preparer.prepare_final_shift_dataframe()
    print("Creation of shifts complete..")
    print("////////////////////////////////////////////////////////////////////////////////////////////////////////")
    print("5. Writing the allocated shifts to a csv file..")
    file_operations.write_output_shifts_to_file(final_shift_information)
    print("File written. Task Complete..")
    print("////////////////////////////////////////////////////////////////////////////////////////////////////////")
